const SET_COUNT = 'SET_COUNT';
const GET_ERROR = 'GET_ERROR';
const SET_CURRENT_USER = 'SET_CURRENT_USER';
const SET_NEW_CARD = 'SET_NEW_CARD';
const GET_ALL_CARDS = 'GET_ALL_CARDS';
const DELETE_SELECTED_CARD = 'DELETE_SELECTED_CARD';
const FILTER_LIST = 'FILTER_LIST';

export {
  SET_COUNT,
  GET_ERROR,
  SET_CURRENT_USER,
  SET_NEW_CARD,
  GET_ALL_CARDS,
  DELETE_SELECTED_CARD,
  FILTER_LIST,
};
