const INC = 'INC';
const DEC = 'DEC';
const GET_ERROR = 'GET_ERROR';
const SET_CURRENT_USER = 'SET_CURRENT_USER';
const SET_NEW_CARD = 'SET_NEW_CARD';
const GET_ALL_CARDS = 'GET_ALL_CARDS';
const DELETE_SELECTED_CARD = 'DELETE_SELECTED_CARD';

export {
  INC,
  DEC,
  GET_ERROR,
  SET_CURRENT_USER,
  SET_NEW_CARD,
  GET_ALL_CARDS,
  DELETE_SELECTED_CARD,
};
